### ISSUE TITLE
Missing class at the install of the module

### ISSUE THREAD

**Issue by peterkenne** [dpdconnect/prestashop16-shipping#1]
Hi, I tried to install the module, but received a "missing class" error.
This seems to be related to the line 21 of the main class dpdconnect.php of the module.
require_once(__DIR__.'/vendor/autoload.php');
I do not find myself nor the directory vendor, nor the class autoload.php.
Am I missing something ?

Thanks, 

Jean-Marc

**Comment by doekia** [comment]
> composer install
but I get the feeling this code is not mature at all

**Comment by peterkenne** [comment]
Hi doekia, if you have a solution for a working DPD module on PrestaShop 1.6, feel free to transmit the info, we are searching for a while. We tried dpdcarrier, dpdbenelux, dpdconnect, and all the last versions seem to have problems. 
Our actual last solution is to use free version of SendCloud and deactivate all other carriers than DPD.
Other possibility ?

**Comment by doekia** [comment]
I have something in progress but I need to run tests prior to publish anything right now

**Comment by peterkenne** [comment]
Don't hesitate if you need some tester, we have some staging environment that are waiting for it ;-)

**Comment by Geert0111** [comment]
did you get things working correct?

**Comment by peterkenne** [comment]
No, actually our client chose for another transporter. Too complex to integrate DPD with PrestaShop actually.

**Comment by dpdplugin** [comment]
When you download the module from the releases page it will include the vendor directory.

**Comment by doekia** [comment]
Did you tested the code this time or it is still the same unworking code?
https://github.com/dpdconnect/prestashop16-shipping/issues/2
