### ISSUE TITLE
What this line is supposed to be? Obviously a bug right now

### ISSUE THREAD

**Issue by doekia** [dpdconnect/prestashop16-shipping#2]
https://github.com/dpdconnect/prestashop16-shipping/blob/38ca9ca972534e4622480d622f63adb02fea9aab/override/controllers/admin/AdminCarrierWizardController.php#L182

**Comment by doekia** [comment]
if (is_array($carrier_zones)) !! ?? !!

Franckly if you have run your code thru an automatied processor to replace all array() by [] and later not tested it it is criminal

**Comment by Geert0111** [comment]
did you get things working correct?

**Comment by dpdplugin** [comment]
This code is not used in the module and will be removed
